# Generated by Django 4.1.4 on 2023-04-27 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(blank=True, max_length=500, null=True)),
                ('item_description', models.TextField(blank=True, max_length=500, null=True)),
                ('quantity_need', models.IntegerField()),
                ('contact_number', models.IntegerField()),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='proposal/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
