# Generated by Django 4.1.4 on 2023-04-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='item_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='item_name',
            field=models.TextField(default=True, max_length=500),
            preserve_default=False,
        ),
    ]
