# Generated by Django 4.1.4 on 2023-04-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_proposal_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='ask_price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
