# Generated by Django 4.1.4 on 2023-03-03 11:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('Company_address', models.TextField(blank=True, max_length=500, null=True)),
                ('GST_number', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15)])),
                ('Phone_number', models.CharField(blank=True, max_length=13)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('currency', models.CharField(max_length=15)),
                ('GST_regitered', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_no', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('online', 'ONLINE'), ('cash', 'CASH'), ('check', 'CHECK'), ('upi', 'UPI'), ('card', 'CARD')], default='cash', max_length=10)),
                ('customer_name', models.CharField(max_length=50)),
                ('Phone_number', models.CharField(blank=True, max_length=13)),
                ('company_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_from', to='home.company')),
                ('company_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_to', to='home.company')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(blank=True, max_length=500, null=True)),
                ('MRP_price_per_unit', models.IntegerField()),
                ('GST_percentage', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('profit_amount', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('item_image', models.ImageField(upload_to='items/')),
                ('created_by_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.invoice')),
                ('ordered_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.items')),
            ],
        ),
    ]
