# Generated by Django 4.1.4 on 2023-03-04 03:21

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=13),
        ),
    ]
