# Generated by Django 4.1.7 on 2023-02-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='hotel_Main_Img',
        ),
    ]
