# Generated by Django 4.1.4 on 2023-03-04 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_company_company_mail_alter_invoice_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='GST_regitered',
        ),
    ]
