# Generated by Django 4.1.4 on 2023-03-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_company_gst_regitered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='GST_number',
            field=models.CharField(max_length=15),
        ),
    ]
