# Generated by Django 4.1.7 on 2023-02-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_company_hotel_main_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='hotel_Main_Img',
            new_name='profile_image',
        ),
    ]
