# Generated by Django 4.1.7 on 2023-02-28 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_hotel_main_img_company_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_no', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('online', 'ONLINE'), ('cash', 'CASH'), ('check', 'CHECK'), ('upi', 'UPI'), ('card', 'CARD')], default='cash', max_length=10)),
                ('customer_name', models.CharField(choices=[('online', 'ONLINE'), ('cash', 'CASH'), ('check', 'CHECK'), ('upi', 'UPI'), ('card', 'CARD')], default='green', max_length=6)),
                ('company_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_from', to='home.company')),
                ('company_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_to', to='home.company')),
            ],
        ),
    ]
