# Generated by Django 4.1.7 on 2023-03-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_invoice_coustomer_mail'),
        ('home', '0005_invoice_coustomer_mail'),
    ]

    operations = [
    ]
