# Generated by Django 4.1.7 on 2023-02-28 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_invoice_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='company_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_from', to='home.company'),
        ),
    ]
