# Generated by Django 4.1.4 on 2023-03-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20230306_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
