# Generated by Django 4.1.7 on 2023-02-28 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_alter_invoice_company_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(blank=True, max_length=500, null=True)),
                ('price_per_unit', models.IntegerField()),
                ('GST_percentage', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('profit_amount', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('item_image', models.ImageField(upload_to='items/')),
                ('created_by_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
