# Generated by Django 4.1.7 on 2023-02-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_invoice_phone_number_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='price_per_unit',
            new_name='MRP_price_per_unit',
        ),
    ]
