# Generated by Django 4.1.4 on 2023-03-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_invoice_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.CharField(default=10000, max_length=20),
            preserve_default=False,
        ),
    ]
