# Generated by Django 4.1.7 on 2023-02-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_price_per_unit_items_mrp_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='profit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
