# Generated by Django 4.1.4 on 2023-03-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_invoice_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
