# Generated by Django 4.1.4 on 2023-03-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_items_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(max_length=20),
        ),
    ]
