# Generated by Django 4.1.4 on 2023-03-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_expanse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expanse',
            old_name='profit_amount',
            new_name='amount',
        ),
    ]
