# Generated by Django 4.1.4 on 2023-04-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_inventoryitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitems',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.items'),
        ),
    ]
